name: pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -race -v ./... -coverprofile ./coverage.txt

    - name: Codecov
      uses: codecov/codecov-action@v3.1.1
      with:
        files: ./coverage.txt

  benchmark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with: { fetch-depth: 1 }

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Gobenchdata
      run: go run go.bobheadxi.dev/gobenchdata@v1 action
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        INPUT_PRUNE_COUNT: 30
        INPUT_GO_TEST_FLAGS: -run=^$
        INPUT_GOBENCHDATA_PARSE_FLAGS: --flat
        # 'push' event only triggers on pushes to main
        INPUT_PUBLISH: ${{ github.event_name == 'push' }}
        INPUT_PUBLISH_BRANCH: publish-benchmarks
